### ISSUE TITLE
please add docs or update README

### ISSUE THREAD

**Issue by micooz** [egoist/notie#2]
In the latest version, `notie` is not a function while new functions were added:

* alert(type, message, seconds)
* confirm(title, yes_text, no_text, yes_callback)
* input(title, submit_text, cancel_text, type,...)

Please make it clear in the docs :)

**Comment by egoist** [comment]
Sorry, I've given the NPM package name `notie` to https://github.com/jaredreich/notie.js

If you still want to use this library try install `corner-notie`, I've updated the README to mention this.
